apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.deployment.appName }}
  name: {{ .Values.deployment.name }}
  namespace: aluno-lucas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.appName }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.appName }}
    spec:
      containers:
        - image: peteindockerhub/hello-rancher:1.0.2
        imagePullPolicy: Always
        name: desafio-helm
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
