apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: aluno-lucas
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.deployment.appName }}